### ISSUE TITLE
A working Demo

### ISSUE THREAD

**Issue by DevashishPrasad** [ZZYuting/MS-G3D_v1#1]
Hello, Thank you for the demo you created. Could you please provide some help regarding how to actually pass a video to the script, installation dependencies. A colab notebook based demo would the best thing.

Thank you again for this repo. A much useful code

**Comment by DevashishPrasad** [comment]
I solved the issue, Thank you for the great code again.... very helpful

**Comment by ZZYuting** [comment]
> I solved the issue, Thank you for the great code again.... very helpful
Hi, I release a more stable demo and useful tools for skeleton-based action recognition.  Welcome to star!
